function [results, coverageTable] = run_test_coverage()
%RUN_TEST_COVERAGE Run normal tests with eligible-source statement coverage.
%
% The source list explicitly excludes the heterogeneous simulator. The
% native simulator tests are serial because the executables use fixed binary
% filenames in the system temporary folder.

% Programmatic statement coverage was introduced in R2023a.
if verLessThan('matlab', '9.14')
    error('xDDx:Tests:CoverageRequiresR2023a', ...
        ['run_test_coverage requires MATLAB R2023a or newer. ' ...
        'Use run_all_tests to run the normal suite without coverage.']);
end

import matlab.unittest.TestRunner
import matlab.unittest.TestSuite
import matlab.unittest.plugins.CodeCoveragePlugin
import matlab.unittest.plugins.codecoverage.CoverageResult

testRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testRoot);
suite = [ ...
    TestSuite.fromFolder(fullfile(testRoot, 'unit'), ...
    'IncludingSubfolders', true), ...
    TestSuite.fromFolder(fullfile(testRoot, 'integration'), ...
    'IncludingSubfolders', true) ...
    ];
sourceFolders = { ...
    fullfile(projectRoot, 'xDDx_lib'), ...
    fullfile(projectRoot, 'holography_toolbox'), ...
    fullfile(projectRoot, 'simulation_toolbox', 'homogeneous_simulatior') ...
    };

coverageFormat = CoverageResult;
runner = TestRunner.withTextOutput;
runner.addPlugin(CodeCoveragePlugin.forFolder(sourceFolders, ...
    'IncludingSubfolders', true, 'Producing', coverageFormat));
results = runner.run(suite);

coverageResults = coverageFormat.Result;
statementSummary = coverageSummary(coverageResults, 'statement');
fileNames = string({coverageResults.Filename}).';
statementsHit = statementSummary(:, 1);
statementsTotal = statementSummary(:, 2);
statementPercent = 100*statementsHit./max(statementsTotal, 1);
coverageTable = table(fileNames, statementsHit, statementsTotal, ...
    statementPercent, 'VariableNames', {'File', 'StatementsHit', ...
    'StatementsTotal', 'StatementPercent'});

fprintf('\nTotal statement coverage: %d/%d (%.1f%%) across %d files.\n', ...
    sum(statementsHit), sum(statementsTotal), ...
    100*sum(statementsHit)/max(sum(statementsTotal), 1), ...
    height(coverageTable));
end
