function catalog = example_regression_catalog()
%EXAMPLE_REGRESSION_CATALOG Mapped non-heterogeneous simulation scripts.
%
% Each entry maps the reorganized script to its location in the legacy xDDx
% project and declares the numeric workspace outputs used for comparison.

catalog = [ ...
    entry('quick_start_flat', 'holography_toolbox/quick_start_flat.m', ...
    'examples/holography_toolbox/quick_start_flat.m', {'vSource'}), ...
    entry('quick_start_spherical', 'holography_toolbox/quick_start_spherical.m', ...
    'examples/holography_toolbox/quick_start_spherical.m', {'vSource'}), ...
    entry('bp_auto_alignment_sf', ...
    'holography_toolbox/alignment_tools/bp_auto_alignment_sf.m', ...
    'examples/holography_toolbox/alignment_tools/bp_auto_alignment_sf.m', ...
    {'vSource'}), ...
    entry('bp_predefined_alignment_sf', ...
    'holography_toolbox/alignment_tools/bp_predefined_alignment_sf.m', ...
    'examples/holography_toolbox/alignment_tools/bp_predefined_alignment_sf.m', ...
    {'vSource'}), ...
    entry('bp_predefined_alignment_transient', ...
    'holography_toolbox/alignment_tools/bp_predefined_alignment_transient.m', ...
    'examples/holography_toolbox/alignment_tools/bp_predefined_alignment_transient.m', ...
    {'vSpectrumSurfTransient', 'vWaveformsSurf'}), ...
    entry('extract_sf_from_transient', ...
    'holography_toolbox/data_preparation_tools/extract_sf_from_transient.m', ...
    'examples/holography_toolbox/data_preparation_tools/extract_sf_from_transient.m', ...
    {'HologramSf.complexPressureAmplitude'}), ...
    entry('power_of_hologram', ...
    'holography_toolbox/data_preparation_tools/power_of_hologram.m', ...
    'examples/holography_toolbox/data_preparation_tools/power_of_hologram.m', ...
    {'powerAtFrequency'}), ...
    entry('bp_sf', 'holography_toolbox/simple_projection_tools/bp_sf.m', ...
    'examples/holography_toolbox/simple_projection_tools/bp_sf.m', {'vSource'}), ...
    entry('fp_sf', 'holography_toolbox/simple_projection_tools/fp_sf.m', ...
    'examples/holography_toolbox/simple_projection_tools/fp_sf.m', {'pField3D'}), ...
    entry('fp_transient', 'holography_toolbox/simple_projection_tools/fp_transient.m', ...
    'examples/holography_toolbox/simple_projection_tools/fp_transient.m', ...
    {'pFieldWaveforms'}), ...
    entry('set_flat_boundary_condition_sf', ...
    'simulation_toolbox/homogeneous_simulatior/set_flat_boundary_condition_sf.m', ...
    'examples/simulation_toolbox/set_flat_boundary_condition_sf.m', ...
    {'pFlatBoundary', 'vFlatBoundary', 'pField3D'}), ...
    entry('transducer_simulation_sf', ...
    'simulation_toolbox/homogeneous_simulatior/transducer_simulation_sf.m', ...
    'examples/simulation_toolbox/transducer_simulation_sf.m', {'pField3D'}), ...
    entry('transducer_simulation_transient', ...
    'simulation_toolbox/homogeneous_simulatior/transducer_simulation_transient.m', ...
    'examples/simulation_toolbox/transducer_simulation_transient.m', ...
    {'pFieldFrames3D'}), ...
    entry('flat_piston_simulation_sf', ...
    'simulation_toolbox/homogeneous_simulatior/validation_tools/flat_piston_simulation_sf.m', ...
    'examples/simulation_toolbox/validation_tools/flat_piston_simulation_sf.m', ...
    {'pField3D', 'pFieldNumerical'}), ...
    entry('spherical_piston_simulation_sf', ...
    'simulation_toolbox/homogeneous_simulatior/validation_tools/spherical_piston_simulation_sf.m', ...
    'examples/simulation_toolbox/validation_tools/spherical_piston_simulation_sf.m', ...
    {'pField3D', 'pFieldNumerical'}) ...
    ];
end

function value = entry(name, newRelativePath, oldRelativePath, outputNames)
value = struct('Name', name, 'NewRelativePath', newRelativePath, ...
    'OldRelativePath', oldRelativePath, 'OutputNames', {outputNames});
end
