classdef ExampleRegressionInterfaceTest < matlab.unittest.TestCase
    %EXAMPLEREGRESSIONINTERFACETEST Public script-selection interface.

    methods (TestClassSetup)
        function addTestPaths(testCase)
            testRoot = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(testRoot));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(testRoot, 'example_regression')));
        end
    end

    methods (Test)
        function testCatalogListsEveryMappedScript(testCase)
            catalog = example_regression_catalog();

            actual = list_simulation_scripts();

            testCase.verifyEqual(height(actual), numel(catalog));
            testCase.verifyEqual(actual.Name, {catalog.Name}.');
        end

        function testUnknownScriptIsRejected(testCase)
            functionCall = @() run_simulation_script_tests( ...
                'Scripts', 'not_a_project_script', ...
                'RunMode', 'new-only', 'SaveReports', false);

            testCase.verifyError(functionCall, ...
                'xDDx:ExampleRegression:UnknownScript');
        end

        function testUnknownReferenceProjectIsRejected(testCase)
            functionCall = @() run_simulation_script_tests( ...
                'Scripts', 'extract_sf_from_transient', ...
                'RunMode', 'new-only', ...
                'ReferenceProject', 'not_a_project_version', ...
                'SaveReports', false);

            testCase.verifyError(functionCall, ...
                'xDDx:ExampleRegression:InvalidReferenceProject');
        end

        function testDefaultReferenceIsXddx(testCase)
            [~, ~, ~, results] = run_simulation_script_tests( ...
                'Scripts', 'extract_sf_from_transient', ...
                'SimulationDevices', 'cpu', ...
                'RunMode', 'new-only', 'SaveReports', false);

            testCase.verifyEqual(results.referenceProject, 'xddx');
            testCase.verifyEqual(results.referenceProjectDir, fullfile( ...
                fileparts(fileparts(fileparts(fileparts(mfilename('fullpath'))))), ...
                'xDDx'));
        end

        function testExplicitReferenceDirectoryTakesPrecedence(testCase)
            projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));

            [~, ~, ~, results] = run_simulation_script_tests( ...
                'Scripts', 'extract_sf_from_transient', ...
                'SimulationDevices', 'cpu', ...
                'RunMode', 'new-only', ...
                'ReferenceProject', 'oldest', ...
                'OldProjectDir', projectRoot, ...
                'SaveReports', false);

            testCase.verifyEqual(results.referenceProject, 'custom');
            testCase.verifyEqual(results.referenceProjectDir, projectRoot);
        end

        function testNewOnlyDataPreparationSelection(testCase)
            [summary, comparison, speed, results] = run_simulation_script_tests( ...
                'Scripts', 'extract_sf_from_transient', ...
                'SimulationDevices', 'cpu', ...
                'RunMode', 'new-only', ...
                'ReferenceProject', 'oldest', ...
                'SaveReports', false);

            testCase.verifyTrue(all(summary.Success));
            testCase.verifyEqual(summary.Script, ...
                {'extract_sf_from_transient.m'});
            testCase.verifyEqual(comparison.OutputName, ...
                {'HologramSf.complexPressureAmplitude'});
            testCase.verifyEqual(height(speed), 1);
            testCase.verifyEqual(results.referenceProject, 'oldest');
            testCase.verifyEqual(results.referenceProjectDir, fullfile( ...
                fileparts(fileparts(fileparts(fileparts(mfilename('fullpath'))))), ...
                'xDDx_old'));
        end
    end
end
