classdef ExampleManifestTest < matlab.unittest.TestCase
    %EXAMPLEMANIFESTTEST Guard source and normal-test project scope.

    methods (Test)
        function testEveryEligibleExampleHasRegressionMapping(testCase)
            projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            catalogPath = fullfile(projectRoot, 'Tests', 'example_regression', ...
                'example_regression_catalog.m');
            catalogText = fileread(catalogPath);
            exampleFiles = [ ...
                dir(fullfile(projectRoot, 'holography_toolbox', '**', '*.m')); ...
                dir(fullfile(projectRoot, 'simulation_toolbox', ...
                'homogeneous_simulatior', '**', '*.m'))];
            exampleNames = erase({exampleFiles.name}, '.m');
            mappedNames = regexp(catalogText, ...
                'entry\(''([^'']+)''', 'tokens');
            mappedNames = cellfun(@(token) token{1}, mappedNames, ...
                'UniformOutput', false);

            missingNames = setdiff(exampleNames, mappedNames);

            testCase.verifyEmpty(missingNames, ...
                'Eligible example scripts are missing from the regression map.');
        end

        function testNormalTestCodeDoesNotReferenceHeterogeneousSimulator(testCase)
            projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            testFiles = dir(fullfile(projectRoot, 'Tests', '**', '*.m'));
            contents = cellfun(@(folder, name) fileread(fullfile(folder, name)), ...
                {testFiles.folder}, {testFiles.name}, 'UniformOutput', false);
            forbidden = ['heterogeneous_' 'simulator'];
            hasForbiddenReference = cellfun(@(text) contains(text, forbidden), contents);
            backendTestFolder = fullfile(projectRoot, 'Tests', ...
                'backend_comparison');
            isBackendComparison = startsWith( ...
                {testFiles.folder}, backendTestFolder);

            testCase.verifyFalse(any( ...
                hasForbiddenReference & ~isBackendComparison));
        end

        function testEligibleMatlabSourcesHaveNoParseErrors(testCase)
            projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            sourceRoots = {fullfile(projectRoot, 'xDDx_lib'), ...
                fullfile(projectRoot, 'holography_toolbox'), ...
                fullfile(projectRoot, 'simulation_toolbox', ...
                'homogeneous_simulatior')};
            sourceFiles = cellfun(@(root) dir(fullfile(root, '**', '*.m')), ...
                sourceRoots, 'UniformOutput', false);
            sourceFiles = vertcat(sourceFiles{:});
            issueLists = arrayfun(@(file) checkcode( ...
                fullfile(file.folder, file.name), '-id'), sourceFiles, ...
                'UniformOutput', false);
            issueMessages = cellfun(@(issues) {issues.message}, issueLists, ...
                'UniformOutput', false);
            parseErrors = cellfun(@(messages) any(contains(lower(messages), ...
                {'parse error', 'syntax error'})), issueMessages);

            testCase.verifyFalse(any(parseErrors), ...
                'At least one eligible MATLAB source file has a parse error.');
        end
    end
end
